server:
  port: 8000
spring:
  profiles:
    active: dev
  application:
    name: taskManager
  datasource:
    password:
    username: root
    url: jdbc:h2:mem:taskManager
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        connection:
          password:
          username: root
          driver_class: org.h2.Driver
          url: jdbc:h2:mem:taskManager
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration,classpath:db/migration/dev
jwt:
  secret: 'jwt-secret-code'
  expiration: 3600000
cors:
  allowed-origin-urls: http://127.0.0.1,http://localhost
