spring:
  application:
    name: taskManager
  datasource:
    password:
    username: root
    url: jdbc:h2:mem:taskManager
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
